version: "2"
services:
  postgresql:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  phoenix:
    image: nikolauska/phoenix
    command: sh -c "while true; do echo Alive; sleep 100; done"
    volumes:
        - ./:/data
    ports:
      - 4000:4000
    links:
      - postgresql:postgres
networks:
  default:
    external:
      name: neoprivatenetdocker_default
